
title: Baby
author: Shamama
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am the UI and Front end designer for the Third Eye Project. My self and Shamama designed the UI design using figma And adobe XD. And after designing it and the UX prototype was done. And then we designed the Front end for the web application.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
